<?php

namespace App\Command;

use Symfony\Component\Console\Command\Command;
use Symfony\Component\Console\Input\InputInterface;
use Symfony\Component\Console\Output\OutputInterface;

class MigrateToPgsqlCommand extends Command
{
    protected static $defaultName = 'cros:migrate-to-pgsql';

    protected function configure()
    {
        parent::configure(); // TODO: Change the autogenerated stub
    }

    protected function execute(InputInterface $input, OutputInterface $output)
    {
        $output->writeln("--== START ==--");

        // TODO: migrate all conferences
        // TODO: migrate all organizations
        // TODO: migrate all users
        // TODO: migrate site info 2018
        // TODO: migrate full archive
        // TODO: migrate speakers 2018
        // TODO: migrate program 2018

        $output->writeln("--== END ==--");
    }
}