<?php

namespace App\Command;

use Symfony\Component\Console\Command\Command;
use Symfony\Component\Console\Input\InputInterface;
use Symfony\Component\Console\Output\OutputInterface;

class MigrateToPgsqlCommand extends Command
{
    protected static $defaultName = 'cros:migrate-to-pgsql';

    protected function configure()
    {
        parent::configure(); // TODO: Change the autogenerated stub
    }

    protected function execute(InputInterface $input, OutputInterface $output)
    {
        $output->writeln("--== START ==--");

        $this->migrateConferences();
        $this->migrateOrganizations();
        $this->migrateUsers();
        $this->migrateArchive();
        $this->migrateSiteInfo2018();
        $this->migrateProgram2018();
        $this->migrateSpeakers2018();

        $output->writeln("--== END ==--");
    }

    // TODO:
    private function migrateConferences()
    {

    }

    // TODO:
    private function migrateOrganizations()
    {

    }

    // TODO:
    private function migrateUsers()
    {

    }

    // TODO:
    private function migrateArchive()
    {

    }

    // TODO:
    private function migrateSiteInfo2018()
    {

    }

    // TODO:
    private function migrateSpeakers2018()
    {

    }

    // TODO:
    private function migrateProgram2018()
    {

    }
}