parameters:
    # Adds a fallback DATABASE_URL if the env var is not set.
    # This allows you to run cache:warmup even if your
    # environment variables are not available yet.
    # You should not need to change this value.
    env(DATABASE_URL): ''

doctrine:
    dbal:
        default_connection: pgsql
        connections:
            pgsql:
                driver: 'pdo_pgsql'
                server_version: '10.5'
                charset: utf8
                default_table_options:
                    charset: utf8
                    collate: utf8_unicode_ci
                url: '%env(resolve:DATABASE_URL)%'
            mysql:
                driver: 'pdo_mysql'
                server_version: '5.7'
                charset: utf8
                default_table_options:
                    charset: utf8
                    collate: utf8_unicode_ci
                url: '%env(resolve:OLD_DATABASE_URL)%'

    orm:
        auto_generate_proxy_classes: true
        entity_managers:
            pgsql:
                connection: pgsql
                naming_strategy: doctrine.orm.naming_strategy.underscore
                auto_mapping: true
                mappings:
                    App:
                        is_bundle: false
                        type: annotation
                        dir: '%kernel.project_dir%/src/Entity'
                        prefix: 'App\Entity'
                        alias: App
            mysql:
                connection: mysql
                naming_strategy: doctrine.orm.naming_strategy.underscore
                mappings:
                    AppOld:
                        is_bundle: false
                        type: annotation
                        dir: '%kernel.project_dir%/src/Old/Entity'
                        prefix: 'App\Old\Entity'
                        alias: AppOld
