<?php

namespace AppBundle\Repository;

/**
 * ApartamentRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class ApartamentRepository extends \Doctrine\ORM\EntityRepository
{
    public function findAllWithIds(){
        $query = $this->getEntityManager()
            ->createQuery('
            SELECT a, ai, ato, u, o FROM AppBundle:Apartament a
            JOIN a.aitoas ai 
            LEFT JOIN ai.atoais ato
            LEFT JOIN ato.user u
            LEFT JOIN u.organization o
            ');
        try{
            return $query->getResult();
        } catch (\Doctrine\ORM\NoResultException $e){
            return null;
        }
    }
}
