<?php

namespace AppBundle\Repository;

/**
 * ApartamentTypeRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class ApartamentTypeRepository extends \Doctrine\ORM\EntityRepository
{
}
