<?php

namespace AppBundle\Repository;

/**
 * AppendTextRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class AppendTextRepository extends \Doctrine\ORM\EntityRepository
{
}
