<?php

namespace AppBundle\Repository;

/**
 * CorpusesRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class CorpusesRepository extends \Doctrine\ORM\EntityRepository
{

}
