<?php

namespace AppBundle\Repository;

/**
 * FlatRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class FlatRepository extends \Doctrine\ORM\EntityRepository
{
    public function findAllToHotel()
    {
        $query = $this->getEntityManager()->createQuery("
            SELECT
              '',
              flat.real_id as ap_num,
              '',
              apart_type.code as category_1,
              apartment.code_hotel as category_2,
              apartment.places as places,
              user.last_name as f,
              user.first_name as i,
              user.middle_name as o,
              org.name as org_name
            FROM
              (SELECT id, room1 AS room, real_id, type_id
               FROM flat
               WHERE room1 IS NOT NULL
               UNION
               SELECT id, room2 AS room, real_id, type_id
               FROM flat
               WHERE room2 IS NOT NULL
               UNION
               SELECT id, room3 AS room, real_id, type_id
               FROM flat
               WHERE room3 IS NOT NULL
               UNION
               SELECT id, room4 AS room, real_id, type_id
               FROM flat
               WHERE room4 IS NOT NULL
               UNION
               SELECT id, room5 AS room, real_id, type_id
               FROM flat
               WHERE room5 IS NOT NULL) as flat
              INNER JOIN apartament_type apart_type ON flat.type_id = apart_type.id
              INNER JOIN apartament_id  apart ON flat.room = apart.id
              INNER JOIN apartament apartment ON apart.apartament_id = apartment.id
              INNER JOIN user_to_apartament uta ON uta.apartaments_id = flat.room
              INNER JOIN user user ON user.id = uta.user_id
              INNER JOIN organization org ON user.organization_id = org.id
            ORDER BY
              ap_num ASC
            ;
        ");

        return $query->getResult();
    }
}
