<?php

namespace AppBundle\Repository;

/**
 * InfoRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class InfoRepository extends \Doctrine\ORM\EntityRepository
{
    /**
     * Find custom text pages
     *
     * @return array The entities.
     */
    public function findAllFree(){
        $aliases = array(
            'targets',
            'place',
            'transfer',
            'terms',
            'result',
            'sponsors',
        );
        $query = $this->getEntityManager()
            ->createQuery('
            SELECT i FROM AppBundle:Info i
            WHERE i.alias NOT IN (:aliases)
            ')
            ->setParameter('aliases', $aliases);

        try{
            return $query->getResult();
        } catch (\Doctrine\ORM\NoResultException $e){
            return null;
        }
    }

    public function findInfoByAlias($alias, $year = false){
	if (!$year) $year = date("Y");
        $query = $this->getEntityManager()
            ->createQuery(
                'SELECT i, itco, conf FROM AppBundle:Info i 
		JOIN i.conftoinfos itco
		JOIN itco.conference conf
		WHERE i.id = itco.infoId AND i.alias = :alias
		AND conf.id = itco.conferenceId AND conf.year = :year' 
            )->setParameter('alias', $alias)
	    ->setParameter('year', $year);

        try{
            return $query->setMaxResults(1)->getOneOrNullResult();
        } catch (\Doctrine\ORM\NoResultException $e){
            return null;
        }
    }


}
