<?php

namespace AppBundle\Repository;

/**
 * InfoToConfRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class InfoToConfRepository extends \Doctrine\ORM\EntityRepository
{
}
