<?php

namespace AppBundle\Repository;

/**
 * LectureRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class LectureRepository extends \Doctrine\ORM\EntityRepository
{

    public function findByDateAndTime(\DateTime $date, \DateTime $startTime, \DateTime $endTime, $title)
    {
        $query = $this->getEntityManager()
            ->createQuery('SELECT u FROM AppBundle:Lecture u
                            WHERE u.date = :date AND u.startTime = :startTime AND u.endTime = :endTime AND u.title = :title')
            ->setParameter('date', $date->format("Y-m-d"))->setParameter('startTime', $startTime->format("H:i:s"))
            ->setParameter('endTime', $endTime->format("H:i:s"))->setParameter('title', $title);
        try 
        {
            return $query->setMaxResults(1)->getOneOrNullResult();
        } 
        catch (\Doctrine\ORM\NoResultException $e) 
        {
            return null;
        }
    }

	public function findAll()
    {
        return $this->findBy(array(), array('date' => 'ASC', 'startTime' => 'ASC'));
    }

	
	public function findByNotInIds($arrayIDs)
	{
		$query = $this->getEntityManager()
				->createQuery('SELECT l from AppBundle:Lecture l
								WHERE l.id NOT IN (:arrayids)')
				->setParameter('arrayids', $arrayIDs);

		try 
        {
            return $query->getResult();
        } 
        catch (\Doctrine\ORM\NoResultException $e) 
        {
            return null;
        }
	}

}
