<?php

namespace AppBundle\Repository;

/**
 * LogsRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class LogsRepository extends \Doctrine\ORM\EntityRepository
{

    /**
     * @param string $date
     * @return object|null
     */
    public function getConnectionOlder($date)
    {
        return $this->createQueryBuilder('l')
            ->where('l.date >= :date')
            ->setParameter('date', $date)
            ->getQuery()
            ->getOneOrNullResult();
    }
}
