<?php

namespace AppBundle\Repository;

/**
 * ManagerGroupRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class ManagerGroupRepository extends \Doctrine\ORM\EntityRepository
{
}
