<?php

namespace AppBundle\Repository;

/**
 * OrganizationStatusRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class OrganizationStatusRepository extends \Doctrine\ORM\EntityRepository
{
}
