<?php

namespace AppBundle\Repository;

/**
 * Organization2Repository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class Organization2Repository extends \Doctrine\ORM\EntityRepository
{
    function testRepo() {
        echo 1234;
    }
}
