<?php

namespace AppBundle\Repository;

/**
 * OrgToConfRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class OrgToConfRepository extends \Doctrine\ORM\EntityRepository
{
}
