<?php

namespace AppBundle\Repository;

/**
 * SpeakerRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class SpeakerRepository extends \Doctrine\ORM\EntityRepository
{
    /**
     * @param string $conf
     * @return object|null
     */
    public function findByConf($conf)
    {
        $query = $this->getEntityManager()
            ->createQuery('
                    SELECT s, u, utc, o, otc, c FROM AppBundle:Speaker s
                    JOIN s.user u
                    LEFT JOIN u.utocs utc
                    JOIN u.organization o
                    LEFT JOIN o.otc otc
                    JOIN otc.conference c
                    WHERE c.id = :id AND s.publish = 1 ORDER BY u.id DESC
                ')->setParameter('id', $conf);
        try{
            return $query->getResult();
        } catch (\Doctrine\ORM\NoResultException $e){
            return null;
        }
    }
}
