<?php

namespace AppBundle\Repository;

/**
 * TypeSponsor
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class TypeSponsorRepository extends \Doctrine\ORM\EntityRepository
{
}
