<?php

namespace AppBundle\Repository;

/**
 * UserToApartamentRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class UserToApartamentRepository extends \Doctrine\ORM\EntityRepository
{
}
