imports:
    - { resource: parameters.yml }
    - { resource: security.yml }
    - { resource: services.yml }

parameters:
    locale: ru
    tg.bot.token: "527782633:AAFPLooKU0KwINR_CwRj7R-1Z_nHv9b5t0o"
    tg.bot.token_test: "560591203:AAGbR2dImWaYdY1LzT5qZfE4wmRoleMU9vc"
    speakers.resize:
        small:
            width: 253
            height: 300
        big:
            width: 277
            height: 350
    sponsor.resize:
        width: 400
        height: 200
framework:
    #esi:             ~
    translator:      { fallbacks: ["%locale%"] }
    secret:          "%secret%"
    router:
        resource: "%kernel.root_dir%/config/routing.yml"
        strict_requirements: ~
    form:            ~
    csrf_protection: false
    validation:      { enable_annotations: true }
    #serializer:      { enable_annotations: true }
    templating:
        engines: ['twig']
    default_locale:  "%locale%"
    trusted_hosts:   ~
    session:
        # http://symfony.com/doc/current/reference/configuration/framework.html#handler-id
        handler_id:  session.handler.native_file
        save_path:   "%kernel.root_dir%/../var/sessions/%kernel.environment%"
    fragments:       ~
    http_method_override: true
    assets: ~
    php_errors:
        log: true

# Twig Configuration
twig:
    debug:            "%kernel.debug%"
    strict_variables: "%kernel.debug%"
    form_themes:
      - bootstrap_3_layout.html.twig
    paths:
      '%kernel.project_dir%/app/Resources/TwigBundle/views': twig_views

# Doctrine Configuration
doctrine:
    dbal:
        driver:   pdo_mysql
        host:     "%database_host%"
        port:     "%database_port%"
        dbname:   "%database_name%"
        user:     "%database_user%"
        password: "%database_password%"
        charset:  UTF8

    orm:
        auto_generate_proxy_classes: "%kernel.debug%"
        naming_strategy: doctrine.orm.naming_strategy.underscore
        auto_mapping: true

# Swiftmailer Configuration
swiftmailer:
    transport:  "%mailer_transport%"
    host:       "%mailer_host%"
    username:   "%mailer_user%"
    password:   "%mailer_password%"
    spool:     { type: memory }

# File Uploader
vich_uploader:
    db_driver: orm
    twig: true

    mappings:
        speakers_avatar:
            uri_prefix: '/uploads/speakers'
            upload_destination: '%kernel.root_dir%/../web/uploads/speakers'
            inject_on_load: false
            delete_on_update: false
            delete_on_remove: false
