imports:
    - { resource: config.yml }

#doctrine:
#    orm:
#        metadata_cache_driver: apc
#        result_cache_driver: apc
#        query_cache_driver: apc

monolog:
    handlers:
        main:
            type:         fingers_crossed
            handler:      syslog
            action_level: info
        console:
            type:  console
        syslog:
            type: syslog
            level: info
            facility: local0

parameters:
    cros_emails: [ 'e.nachuychenko@nag.ru', 'a.gazetdinov@nag.ru', 'esuzev@nag.ru', 'cros@nag.ru' ]

twig:
    globals:
        theme_template: 'base.html.twig'
