# To get started with security, check out the documentation:
# http://symfony.com/doc/current/security.html
security:

    encoders:
        AppBundle\Entity\Organization:
            algorithm: bcrypt
        AppBundle\Entity\User:
            algorithm: bcrypt

    # http://symfony.com/doc/current/security.html#b-configuring-how-users-are-loaded
    providers:
        chain_provider:
          chain:
            providers: [org_db, user_db]
        in_memory:
            memory: ~
        org_db:
            entity: { class: AppBundle:Organization }
        user_db:
            entity: { class: AppBundle:User }


    firewalls:
        # disables authentication for assets and the profiler, adapt it according to your needs
        dev:
            pattern: ^/(_(profiler|wdt)|css|images|js)/
            security: false

        default:
            logout_on_user_change: true
            anonymous: ~
            form_login:
                login_path: members
                check_path: login
                use_referer: true
                require_previous_session: false
            logout:
                path: logout
                target: members
            provider: chain_provider

    access_control:
        # require ROLE_ADMIN for /admin*
        - { path: ^/admin/table, roles: ROLE_MANAGER }
        - { path: ^/admin/org, roles: ROLE_MANAGER }
        - { path: ^/admin, roles: ROLE_ADMIN }
        - { path: ^/profile, roles: ROLE_ORG }
        - { path: ^/registration2, roles: ROLE_ORG}
        - { path: ^/registration3, roles: ROLE_ORG}

    role_hierarchy:
        ROLE_ORG: ROLE_USER
        #ROLE_MANAGER: ROLE_ORG
        ROLE_ADMIN:   ROLE_MANAGER
        ROLE_SUPER_ADMIN: ROLE_ADMIN
