# Learn more about services, parameters and containers at
# http://symfony.com/doc/current/service_container.html
parameters:
#    parameter_name: value
    lectures.sheets.client_secret: "%kernel.root_dir%/google_sheets/google_client_secret.json"
    lectures.sheets.credentials_path: "%kernel.root_dir%/google_sheets/cros.google-sheets.credentials.json"

services:
#    service_name:
#        class: AppBundle\Directory\ClassName
#        arguments: ["@another_service_name", "plain_value", "%parameter_name%"]
  resizeImages:
    class: AppBundle\Service\ResizeImages