parameters:
    invite_bcc_emails: ['e.nachuychenko@nag.ru']
    invoice_bcc_emails: ['e.nachuychenko@nag.ru']
    become_sponsor_bcc_emails: ['e.nachuychenko@nag.ru']
    become_speaker_bcc_emails: ['e.nachuychenko@nag.ru']
