<?php

namespace App\Repository;
use Doctrine\ORM\EntityRepository;
use Doctrine\ORM\Query;

/**
 * LectureRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class LectureRepository extends EntityRepository
{
    public function findByNotInIds($arrayIDs)
	{
		$query = $this->getEntityManager()
				->createQuery('SELECT l from App:Lecture l
								WHERE l.id NOT IN (:arrayids)')
				->setParameter('arrayids', $arrayIDs);

		try 
        {
            return $query->getResult();
        } catch (\Doctrine\ORM\NoResultException $e) {
            return null;
        }
	}


    public function findByHallIdNotNull($date)
    {
        $qb = $this->createQueryBuilder('l');

        $result = $qb
            ->where('l.date = ?1')
            ->andWhere($qb->expr()->isNotNull('l.hallId'))
            ->orderBy('l.startTime', 'ASC')
            ->setParameter('1', $date);

        try{
            return $result->getQuery();
        } catch (\Doctrine\ORM\NoResultException $e){
            return null;
        }
    }

}
