<?php

namespace App\Repository;

/**
 * SpeakerReportsRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class SpeakerReportsRepository extends \Doctrine\ORM\EntityRepository
{
    /**
     * @param string $conf
     * @return object|null
     */
    public function findByIdReports($id)
    {
        $query = $this->getEntityManager()
            ->createQuery('  SELECT res FROM App:SpeakerReports res
                    WHERE res.id = :id
                ')->setParameter('id', $id);
        try{
            return $query->getResult();
        } catch (\Doctrine\ORM\NoResultException $e){
            return null;
        }
    }
}
