monolog:
    handlers:
        main:
            type:         fingers_crossed
            handler:      syslog
            action_level: notice
        console:
            type:  console
        syslog:
            type: syslog
            level: notice
            facility: local0
        deduplicated:
            type: deduplication
            handler: filter
        filter:
            type: filter
            min_level: notice
            max_level: critical
            handler: swift
        swift:
            type: swift_mailer
            from_email: 'error@nag.ru'
            to_email: ['e.suzev@nag.ru']
            subject: 'Ошибка на сайте cros.nag.ru'
            level: debug
            formatter: monolog.formatter.html
            content_type: text/html
parameters:
    cros_emails: [ 'e.nachuychenko@nag.ru', 'a.gazetdinov@nag.ru', 'esuzev@nag.ru', 'cros@nag.ru' ]