parameters:
    invite_bcc_emails: ['e.nachuychenko@nag.ru', 'p.milenin@nag.ru']
    invoice_bcc_emails: ['e.nachuychenko@nag.ru', 'gz@nag.ru']
    become_sponsor_bcc_emails: ['e.nachuychenko@nag.ru', 'cros@nag.ru']
    become_speaker_bcc_emails: ['e.nachuychenko@nag.ru', 'cros@nag.ru']
    failed_auto_invoice_emails: ['e.nachuychenko@nag.ru']
